#lang racket
(display "Вариант 1\n")
(display "Вычисление объема куба.\n")
(display "Введите длину ребра(см) и нажмите клавишу <Enter> = ")
(define a(read))
(define (v x)
  (*(* x x) x))
(display (format "Объем куба: ~a куб.см\n\n" (v a)))

(display "Вариант 4\n")
(display "Вычисление стоимости покупки.\n")
(display "Введите исходные данные:\n")
(display "Цена одного киллограмма яблок(руб.) = ")
(define cena(read))
(display "Вес яблок(кг) = ")
(define ves(read))
(define (st x y)
  (* x y))
(display (format "Стоимость покупки: ~a руб.\n\n" (st cena ves)))

(display "Вариант 5\n")
(display "Вычисление сопротивления электрической цепи.\n")
(display "Введите исходные данные:\n")
(display "Величина первого сопротивления(Ом) = ")
(define R1(read))
(display "Величина второго сопротивления(Ом) = ")
(define R2(read))
(define (R x y)
  (/ 1 (+ (/ 1 x) (/ 1 y))))
(display (format "Сопротивление цепи: ~a Ом" (R R1 R2)))